services:
  mssql:
    image: 'mcr.microsoft.com/azure-sql-edge:latest'
    cap_add: ["SYS_PTRACE"]
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: $howMeTheMon3y!
      MSSQL_PID: 'Developer'
    volumes:
      - ./mssql:/var/opt/mssql
    hostname: mssql
