const mockdata = {
    confirmationMessage: 'Confirmation message\n',
    resetConfirmationMessage: 'Reset Confirmation message\n',
    submitSuccessMessage: '<p>THANK YOU!</p>',
    showSummarizedData: false,
    elementsArea: [
        {
            displayOption: '',
            tag: null,
            contentLink: {
                id: null,
                workId: null,
                guidValue: '47857f2e-014e-40bd-a10e-3145e38a754c',
                providerName: null,
                url: null,
                language: { link: null, displayName: 'English', name: 'en' },
                expanded: {
                    autoComplete: null,
                    required: false,
                    requiredMessage: null,
                    validators: [],
                    elementName: '__field_92',
                    contentLink: {
                        id: null,
                        workId: null,
                        guidValue: '47857f2e-014e-40bd-a10e-3145e38a754c',
                        providerName: null,
                        url: null,
                        language: {
                            link: null,
                            displayName: 'English',
                            name: 'en',
                        },
                        expanded: null,
                    },
                    name: 'New form element',
                    language: {
                        link: null,
                        displayName: 'English',
                        name: 'en',
                    },
                    existingLanguages: [
                        { link: null, displayName: 'English', name: 'en' },
                    ],
                    masterLanguage: null,
                    contentType: ['Block', 'TextboxElementBlock'],
                    parentLink: {
                        id: null,
                        workId: null,
                        guidValue: 'b1f5a6bc-4e73-452f-b83a-853a33db7fdf',
                        providerName: null,
                        url: '/contentassets/b1f5a6bc4e73452fb83a853a33db7fdf/',
                        expanded: null,
                    },
                    routeSegment: null,
                    url: null,
                    changed: '2024-06-10T12:44:29Z',
                    created: '2024-06-10T12:44:29Z',
                    startPublish: '2024-06-10T12:44:29Z',
                    stopPublish: null,
                    saved: '2024-06-10T12:44:29Z',
                    status: 'Published',
                    label: 'Text',
                },
            },
            inlineBlock: { contentType: [] },
        },
    ],
};

export default mockdata;
