const mockdata = {
    contentLink: {
        id: null,
        workId: null,
        guidValue: 'a631f24e-b495-4b32-9ec1-d988dc04cd9f',
        providerName: null,
        url: null,
        language: { link: null, displayName: 'English', name: 'en' },
        expanded: null,
    },
    name: 'Form',
    language: { link: null, displayName: 'English', name: 'en' },
    existingLanguages: [{ link: null, displayName: 'English', name: 'en' }],
    masterLanguage: null,
    contentType: ['Block', 'FormContainerBlock'],
    parentLink: {
        id: null,
        workId: null,
        guidValue: 'a465ef09-55ee-4c94-8cb1-4190f9d1ae8f',
        providerName: null,
        url: '/contentassets/a465ef0955ee4c948cb14190f9d1ae8f/',
        expanded: null,
    },
    routeSegment: null,
    url: null,
    changed: '2024-06-10T12:44:15Z',
    created: '2024-06-10T12:44:15Z',
    startPublish: '2024-06-10T12:44:15Z',
    stopPublish: null,
    saved: '2024-06-10T12:44:34Z',
    status: 'Published',
    title: 'Form title',
    allowToStoreSubmissionData: true,
    description: 'Description',
    showSummarizedData: false,
    confirmationMessage: 'Confirmation message\n',
    resetConfirmationMessage: 'Reset Confirmation message\n',
    submitSuccessMessage: '<p>THANK YOU!</p>',
    allowAnonymousSubmission: true,
    allowMultipleSubmission: true,
    showNavigationBar: true,
    allowExposingDataFeeds: false,
    focusOnForm: false,
    partialSubmissionRetentionPeriod: 'EPiServer.RetentionPolicy.Default',
    finalizedSubmissionRetentionPeriod: 'EPiServer.RetentionPolicy.Default',
    elementsArea: [
        {
            displayOption: '',
            tag: null,
            contentLink: {
                id: null,
                workId: null,
                guidValue: '47857f2e-014e-40bd-a10e-3145e38a754c',
                providerName: null,
                url: null,
                language: { link: null, displayName: 'English', name: 'en' },
                expanded: {
                    autoComplete: null,
                    required: false,
                    requiredMessage: null,
                    validators: [],
                    elementName: '__field_92',
                    contentLink: {
                        id: null,
                        workId: null,
                        guidValue: '47857f2e-014e-40bd-a10e-3145e38a754c',
                        providerName: null,
                        url: null,
                        language: {
                            link: null,
                            displayName: 'English',
                            name: 'en',
                        },
                        expanded: null,
                    },
                    name: 'New form element',
                    language: {
                        link: null,
                        displayName: 'English',
                        name: 'en',
                    },
                    existingLanguages: [
                        { link: null, displayName: 'English', name: 'en' },
                    ],
                    masterLanguage: null,
                    contentType: ['Block', 'TextboxElementBlock'],
                    parentLink: {
                        id: null,
                        workId: null,
                        guidValue: 'b1f5a6bc-4e73-452f-b83a-853a33db7fdf',
                        providerName: null,
                        url: '/contentassets/b1f5a6bc4e73452fb83a853a33db7fdf/',
                        expanded: null,
                    },
                    routeSegment: null,
                    url: null,
                    changed: '2024-06-10T12:44:29Z',
                    created: '2024-06-10T12:44:29Z',
                    startPublish: '2024-06-10T12:44:29Z',
                    stopPublish: null,
                    saved: '2024-06-10T12:44:29Z',
                    status: 'Published',
                    label: 'Text',
                },
            },
            inlineBlock: { contentType: [] },
        },
    ],
};

export default mockdata;
